version: "3.2"

services:
 cloth_service:
  container_name: cloth_service
  hostname: cloth-service
  image: vielen1991/kids.shop:0.0.3-SNAPSHOT
  environment:
   - app.elasticsearch.username=$ELASTIC_USERNAME
   - app.elasticsearch.password=$ELASTIC_PASSWORD
   - app.elasticsearch.jks-password=$JKS_PASSWORD
   - app.elasticsearch.jks-store-path=$JKS_PATH
   - app.elasticsearch.hostAndPort=elasticsearch
   - server.port=9191  
  volumes:
   - type: bind
     source: $ELK_STACK_DIR/certificates
     target: /certs     
  ports:
   - 9191:9191
  networks:
   - elk_stack

networks:
 elk_stack:
  driver: bridge       
