version: "3.2"

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3-management
    volumes:
      - type: bind
        source: $RABBITMQ_WORK_DIR/etc
        target: /etc/rabbitmq
      - type: bind
        source: $RABBITMQ_WORK_DIR/data
        target: /var/lib/rabbitmq
      - type: bind
        source: $RABBITMQ_WORK_DIR/logs
        target: /var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - elk_stack

networks:
  elk_stack:
    driver: bridge
