apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:latest
        resources:
          limits:
            memory: "1Gi"
            cpu: "512m"
        ports:
        - containerPort: 9092
        env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper-service:2181"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://localhost:9092"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"   
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  type: LoadBalancer
  ports:
  - name: "kafka-port"
    protocol: TCP
    port: 9092
    targetPort: 9092