apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-development
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        resources:
          limits:
            memory: "512Mi"
            cpu: "2048m"
        ports:
        - containerPort: 5672
        - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  type: LoadBalancer
  ports:
  - name: "rabbit"
    port: 5672
    targetPort: 5672
    nodePort: 30672
  - name: "management"
    port: 15672
    targetPort: 15672
    nodePort: 30673